### ISSUE TITLE
Issue when running sample code 

### ISSUE THREAD

**Issue by k30r88** [mkamka/lora_decrypt#1]
I tried your sample program and installed dependency. Got this error message : 

            sourceBuffer.copy(targetBuffer, targetStart, sourceStart, sourceEn
                         ^
TypeError: Object #<Uint8Array> has no method 'copy'
    at copyBuffer (/home/mk/lorawan/node_modules/aes-js/index.js:130:26)
    at ModeOfOperationECB.encrypt (/home/mk/lorawan/node_modules/aes-js/index.js:390:13)
    at Object.exports.lora_decrypt (/home/mk/lorawan/node_modules/lora-decrypt/lora_decrypt.js:56:25)
    at Object.<anonymous> (/home/mk/lorawan/test.js:6:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

Have any idea ?

**Comment by mvcf10** [comment]
@k30r88 Try with my fork. http://github.com/mvcf10/lora_decrypt
